name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Create VPS if it doesn't exist
      id: create-vps
      run: |
        if ! doctl compute droplet list | grep -q 'mautic-vps'; then
          doctl compute droplet create mautic-vps --image docker-20-04 --size s-1vcpu-1gb --region nyc1 --ssh-keys ${{ secrets.DIGITALOCEAN_SSH_FINGERPRINT }} --wait --user-data-file setup.sh --enable-monitoring
          echo "droplet_created=true" >> $GITHUB_ENV
        else
          echo "Droplet 'mautic-vps' already exists."
          echo "droplet_created=true" >> $GITHUB_ENV
        fi

    - name: Get Droplet IP
      id: get-droplet-ip
      run: |
        echo "Droplet IP: $(doctl compute droplet get mautic-vps --format PublicIPv4 --no-header)"
        echo "ip=$(doctl compute droplet get mautic-vps --format PublicIPv4 --no-header)" >> $GITHUB_ENV

    - name: Setup SSH Key
      if: steps.create-vps.outputs.droplet_created == 'true'
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 700 ~/.ssh/
        chmod 600 ~/.ssh/id_rsa
        ssh-keygen -R ${{ env.ip }} || true
        ssh-keyscan -H ${{ env.ip }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGE_GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: docker.pkg.github.com/${{ github.repository }}/user/app:latest

    - name: Deploy Docker Compose app
      run: |
        # Pull the newly built image
        doctl compute ssh mautic-vps -- docker pull docker.pkg.github.com/${{ github.repository }}/user/app:latest

        # Run the new version of the app
        doctl compute ssh mautic-vps -- docker-compose up -d
